src/Entity/User/Admin.php
<?php

namespace App\Entity\User;

use App\Repository\User\AdminRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=AdminRepository::class)
 * @ORM\Table(name="app_user_admin")
 */
class Admin implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/InviteController.php
<?php

namespace App\Controller;

use App\Entity\User\Guest;
use App\Security\AppAuthenticator;
use App\Service\JWTManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class InviteController extends AbstractController
{
    /**
     * @Route("/invite/{secret}", name="app_invite", defaults={"secret": "none"})
     *
     * @param JWTManager $jwtManager
     * @param Guest|null $guest
     * @return Response
     */
    public function index(JWTManager $jwtManager, Guest $guest = null): Response
    {
        if (!$this->getUser()) {
            if ($guest) {
                $jwtToken   = $jwtManager->encode(['login' => $guest->getLogin()]);
                $authCookie = Cookie::create(AppAuthenticator::COOKIE_NAME, $jwtToken, strtotime('2030-01-01'));

                $response = new Response();
                $response->headers->setCookie($authCookie);
            } else {
                return $this->redirectToRoute('app_homepage');
            }
        } else {
            $guest = $this->getUser();
        }

        return $this->render(
            'invite/index.html.twig',
            [
                'guest'     => $guest,
                'confirmed' => $this->isConfirmed($guest)
            ],
            $response ?? null
        );
    }

    /**
     * @Route(path="/invite_confirm", name="app_invite_confirmation")
     *
     * @param Request $request
     * @return JsonResponse|RedirectResponse
     */
    public function confirm(Request $request): Response
    {
        $user    = $this->getUser();
        $success = false;

        if (!$user instanceof Guest) {
            return $this->redirectToRoute('app_homepage');
        }

        $confirmation = $request->get('confirmation');

        switch ($confirmation) {
            case "dismiss":
                $user->setConfirmations(['dismiss']);
                break;
            case "submit":
                $user->setConfirmations($user->getPersons());
                break;
            default:
                $user->setConfirmations([$confirmation]);
        }

        $this->getDoctrine()->getManager()->flush();

        if (!$request->isXmlHttpRequest()) {
            return $this->redirectToRoute('app_invite');
        }

        return $this->json(['success' => $success]);
    }

    private function isConfirmed(Guest $guest): bool
    {
        return count($guest->getConfirmations()) > 0;
    }
}

templates/invite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Приглашение{% endblock %}

{% block header %}
    <header id="fh5co-header" class="fh5co-cover fh5co-cover-xs fh5co-cover-letter" role="banner">
        <div class="overlay"></div>
        <div class="fh5co-container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div class="display-t">
                        <div class="display-tc animate-box" data-animate-effect="fadeIn">
                            {% if (guest.title) %}
                                <h1>{{ guest.title }}</h1>
                            {% else %}
                                <h1>Уважаемый, {{ guest.username }}</h1>
                            {% endif %}
                            {% if (guest.message) %}
                                <h2>{{ guest.message|raw }}</h2>
                            {% else %}
                                <h2>приглашаем вас на нашу свадьбу</h2>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div id="fh5co-invite-video">
        <div class="container">
            <div class="row">
                <div class="embed-responsive embed-responsive-16by9">
                    <video id="invite-video" class="embed-responsive-item" src="{{ asset('video/invite.mp4') }}" controls></video>
                </div>
            </div>
            <div class="row">
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Текст приглашения.
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <h2>Здравствуйте, леди и лорды!</h2>

                                <p>
                                    Спешим сообщить вам приятное известие.
                                    Вот уже совсем близко волшебный день.
                                    Праздник настоящей любви - Свадьба.
                                </p>
                                <p>
                                    Которая состоится в древнем замке, четвёртого дня, тёплого июня, нынешнего года.
                                </p>
                                <p>
                                    Благородный рыцарь Александр и дама его сердца Алла, ждут вас на вечерний пир и рыцарский турнир, который состоится в усадьбе Орехово, по улице Пржевальского 14.
                                </p>
                                <p>
                                    Вороты замка откроются в 17:00.
                                </p>
                                <p>
                                    Торжественная церемония заключения брака состоится в 17:30.
                                </p>
                                <p>
                                    Торжество, посвящённое этому счастливому дню, не может пройти без дорогих и близких людей.
                                </p>
                                <p>
                                    Одарите это событие своим вниманием и разделите радость этого дня.
                                </p>
                                <p>
                                    Просим подтвердить ваше присутствие
                                </p>

                                <p>P. S. По возможности, приходите в костюмах, у вас получатся атмосферные фото )</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="confirmation" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document" style="top: 25vh">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">
                        {% if (confirmed) %}
                            Спасибо, что подтвердили свое присутсвие, если передумаете, то сообщите нам заранее.
                        {% else %}
                            Пожалуйста, подтвердите свое присутствие.
                        {% endif %}
                    </h4>
                </div>
                {% if (not confirmed) %}
                <div class="modal-body">
                    <form method="post" action="{{ path('app_invite_confirmation') }}">
                        {% if (guest.persons|length > 1) %}
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="confirmation" value="submit">
                                    Мы придем вместе
                                </button>
                            </div>
                            {% for person in guest.persons %}
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary" name="confirmation" value="{{ person }}">
                                        Может быть только {{ person }}
                                    </button>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <button type="submit" class="btn btn-default" name="confirmation" value="dismiss">
                                    К сожалению, мы не сможем прийти
                                </button>
                            </div>
                        {% else %}
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="confirmation" value="submit">
                                    Я обязательно приду
                                </button>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-default" name="confirmation" value="dismiss">
                                    К сожалению, я не смогу прийти
                                </button>
                            </div>
                        {% endif %}
                    </form>
                </div>
                {% else %}
                {% endif %}
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function () {
            let video = $('#invite-video');
            video.trigger('play');

            video.on('ended', function (e) {
                $('#confirmation').modal('show');
            })
        });
    </script>
{% endblock %}