src/Entity/Gallery/Folder.php
<?php

namespace App\Entity\Gallery;

use App\Repository\Gallery\FolderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=FolderRepository::class)
 * @ORM\Table(name="app_gallery_folder")
 */
class Folder
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=180)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Photo::class, mappedBy="folder")
     */
    private $photos;

    /**
     * @ORM\Column(type="integer")
     */
    private $size = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Photo::class)
     */
    private $thumbnail;

    public function __toString()
    {
        return (string)$this->name;
    }

    public function __construct()
    {
        $this->photos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setFolder($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getFolder() === $this) {
                $photo->setFolder(null);
            }
        }

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->photos->count();
    }

    public function increaseSize(): self
    {
        $this->size++;

        return $this;
    }

    public function decreaseSize(): self
    {
        $this->size--;

        return $this;
    }

    public function getThumbnail(): ?Photo
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?Photo $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }
}

src/Entity/Gallery/Photo.php
<?php

namespace App\Entity\Gallery;

use App\Repository\Gallery\PhotoRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PhotoRepository::class)
 * @ORM\Table(name="app_gallery_photo")
 */
class Photo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Folder::class, inversedBy="photos")
     * @ORM\JoinColumn(nullable=true)
     */
    private $folder;

    /**
     * @ORM\Column(type="string", length=180)
     *
     * @Assert\NotBlank()
     */
    private $fileName;

    public function __toString()
    {
        return (string)$this->fileName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFolder(): ?Folder
    {
        return $this->folder;
    }

    public function setFolder(?Folder $folder): self
    {
        if ($this->folder instanceof Folder) {
            $this->folder->decreaseSize();
        }

        $this->folder = $folder;
        $this->folder->increaseSize();

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getFullPath(): string
    {
        return sprintf('%s/%s', self::getBasePath(), $this->getFileName());
    }

    public static function getBasePath(): string
    {
        return 'uploads/photo';
    }
}

src/Controller/GalleryController.php
<?php

namespace App\Controller;

use App\Entity\Gallery\Folder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class GalleryController extends AbstractController
{
    /**
     * @Route("/gallery/{slug}", name="app_gallery")
     */
    public function index(Folder $folder): Response
    {
        return $this->render(
            'gallery/index.html.twig',
            [
                'folder' => $folder,
                'photos' => $folder->getPhotos()
            ]
        );
    }
}

templates/gallery/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Галерея{% endblock %}

{% block header %}
    <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url({{ asset(folder.thumbnail.fullPath) }});">
        <div class="overlay"></div>
        <div class="fh5co-container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div class="display-t">
                        <div class="display-tc animate-box" data-animate-effect="fadeIn">
                            <h1>{{ folder.name }}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div id="fh5co-gallery">
        <div class="container">
            <div class="row row-bottom-padded-md">
                <div class="col-md-12">
                    <ul id="fh5co-gallery-list">
                        {% for photo in photos %}
                            <li class="one-third animate-box image-popup" data-animate-effect="fadeIn"
                                style="background-image: url({{ asset(photo.fullPath) }}); "
                                data-mfp-src="{{ asset(photo.fullPath) }}"
                                data-name="{{ photo.fileName }}">
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row">
                <div style="display: flex; align-items: center">
                    <a href="#" class="btn btn-block btn-lg btn-default download">Скачать все</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function() {
            $('.image-popup').magnificPopup({type:'image'});
            $('.download').on('click', function (e) {
                e.preventDefault();
                $('.image-popup').each(function (i, item) {
                    let imageData = $(item);
                    saveAs(imageData.data('mfp-src'), imageData.data('name'));
                });
            });
        });
    </script>
{% endblock %}